apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: cluster-policy-deny-attach
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CONNECT"]
      resources:   ["pods/attach"]
  failurePolicy: Fail
  validations:
  - expression: "false"
    message: "attach is not allowed"
