apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: cluster-policy-exec
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CONNECT"]
      resources:   ["pods/exec"]
  failurePolicy: Fail
  validations:
  - expression: "false"
    message: "exec to pod has occurred"
    reason: "High"
