apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: deny-pods-without-app-label-binding
spec:
  policyName: deny-pods-without-app-label
  matchResources:
    namespaceSelector:
      matchLabels:
        vap: enabled