apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: cluster-policy-deny-portforward
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["UPDATE", "CONNECT"]
      resources:   ["pods/portforward"]
  failurePolicy: Fail
  validations:
  - expression: "false"
    message: "portforward is not allowed"
