apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: cluster-policy-portforward
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["UPDATE", "PATCH", "CONNECT"]
      resources:   ["pods/portforward"]
  failurePolicy: Fail
  validations:
  - expression: "false"
    message: "portforward in pod has occurred"
    reason: "High"
