apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    admission-policy-test: abc
    app.kubernetes.io/name: myApp
  annotations:
    container.apparmor.security.beta.kubernetes.io/sleep: runtime/default
spec:
  containers:
  - name: sleep
    image: alpine
    command: ["sudo", sh"]
    args: ["-c", "while true; do sleep 1; done"]
    securityContext:
      capabilities:
        add:
        - SYS_ADM
        drop:
        - NET_RAW
    env :
      - name : azure_batch_key
