apiVersion: v1
kind: PodTemplate
metadata:
  name: test-podtemplate
  labels:
    admission-policy-test: abc
template:
  metadata:
    labels:
      label: test-podtemplate
  spec:
    containers:
    - name: sleep
      image: alpine
      command: ["sh"]
      args: ["-c", "while true; do sleep 1; done"]
