apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: placeholder
spec:
  policyName: placeholder
  validationActions: [Deny]
  paramRef:
    name: placeholder
    parameterNotFoundAction: Deny
  matchResources:
    objectSelector:
      matchLabels:
        admission-policy-test: abc