apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replicationcontroller
  labels:
    admission-policy-test: abc
spec:
  replicas: 1
  selector:
    label: test-replicationcontroller
  template:
    metadata:
      labels:
        label: test-replicationcontroller
    spec:
      containers:
      - name: sleep
        image: alpine
        command: ["sh"]
        args: ["-c", "while true; do sleep 1; done"]
